[project]
name = "todo-fm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pytest>=8.4.1",
    "pytest-html>=4.1.1",
    "pytest-icdiff>=0.9",
    "pytest-sugar>=1.0.0",
]
